name: build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install arm64 crossbuilding toolchain
        run: sudo apt update && sudo apt install -qq crossbuild-essential-arm64
      - name: Setup linker for crossbuilding arm64
        run: |
          cat >>~/.cargo/config <<EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
      - name: Add arm64 target to rustup
        run: rustup target add aarch64-unknown-linux-gnu
      - name: Build
        run: cargo build --verbose --target aarch64-unknown-linux-gnu
